blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/create', views.create, name='create'),
    path('postcreate', views.postcreate, name='postcreate'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.show_archive, name='post_archive'),
    path('archive/<int:year>', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today'),
]

historydb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('repo/', include('repo.urls')),
    path('blog/', include('blog.urls')),
    path('rest_api_test/', include('rest_api_test.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.urls import reverse_lazy
#from django.core.urlresolvers import reverse

#from django.shortcuts import resolve_url
#from django.shortcuts import redirect

class Post(models.Model):
    #author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    #title = models.CharField(max_length=200)
    #text = models.TextField()
    #pub_date = models.DateTimeField(default=timezone.now)

    title = models.CharField(verbose_name='TITLE', max_length=100)
    content = models.TextField('CONTENT', default='')
    pub_date = models.DateTimeField('PUBLISH DATE', default = timezone.now)
    mod_date = models.DateTimeField('MODIFY DATA', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-mod_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('blog:post_detail', args=(self.id,))

    def get_previous(self):
        return self.get_previous_by_mod_date()

    def get_next(self):
        return self.get_next_by_mod_date()

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, TodayArchiveView, YearArchiveView, MonthArchiveView, DayArchiveView

from blog.models import Post

# Create your views here.

class PostLV(ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 2

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'mod_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'mod_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'mod_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'mod_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'mod_date'

def show_archive(request):
    latest_post_list = Post.objects.order_by('-pub_date')[:50]
    context = {
        'latest_post_list':latest_post_list,
        }
    return render(request, 'blog/post_archive.html', context)

def create(request):
    return render(request, 'blog/post_create.html')

from django.shortcuts import redirect
from datetime import datetime
from django.urls import reverse_lazy

def postcreate(request):
    post = Post()

    post.title = request.GET['title']
    post.content = request.GET['body']
    post.pub_date = datetime.now()
    post.mod_date = datetime.now()
    post.save()

    return redirect(reverse_lazy('blog:post_archive'))

blog/templates/blog/post_archive.html
<!-- blog>templates>blog>post_archive.html -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
  </head>

  <body>
    <p>Post Archives until {% now "N d, Y" %}</p>
    <span>
      <a href="{% url 'blog:create' %}">Create</a>
    </span>

    {% if latest_post_list %}
    <ul>
      {% for post in latest_post_list %}
      <li>{{ post.mod_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;<a href="{{ post.get_absolute_url }}"<strong>{{ post.title }}</strong></a></li>
      {% endfor %}
    </ul>
    {% else %}
    <p> No entries are available.</p>
    {% endif %}

  </body>
</html>

blog/templates/blog/post_archive_day.html
<!-- blog>templates>blog>post_archive_day.html -->
<head>
  <meta charset="utf-8">
  <title>CNT Blog</title>
</head>

<body>
  <p>Post Archives until {{ month|date:"N d, Y" }}</p>

  <div>
  <ul>
    {% for post in object_list %}
    <li>
      {{ post.mod_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp; <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
    </li>
    {% endfor %}
  </ul>
  </div>
</body>

blog/templates/blog/post_archive_month.html
<!-- blog>templates>blog>post_archive_month.html -->
<head>
  <meta charset="utf-8">
  <title>CNT Blog</title>
</head>

<body>
  <p>Post Archives until {{ month|date:"N, Y" }}</p>

  <div>
  <ul>
    {% for post in object_list %}
    <li>
      {{ post.mod_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp; <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
    </li>
    {% endfor %}
  </ul>
  </div>
</body>

blog/templates/blog/post_archive_year.html
<!-- blog>templates>blog>post_archive_year.html -->
<head>
  <meta charset="utf-8">
  <title>CNT Blog</title>
</head>

<body>
  <p>Post Archives until {{ year|date:"Y" }}</p>

  <ul>
    {% for date in date_list %}
    <li>
      <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'m' %}">{{ date|date:'F' }}</a>
    </li>
    {% endfor %}
  </ul>
  <div></div>
  <div>
    <ul>
      {% for post in object_list %}
      <li>{{ post.mod_date|date:"Y-m-d" }}%nbsp;<a href="{{ post.get_absolute_url }}"<strong>{{ post.title }}</strong></a></li>
      {% endfor %}
    </ul>
  </div>

</body>

blog/templates/blog/post_create.html
<!-- blog>templates>blog>post_create.html -->

<head>
  <meta charset="utf-8">
  <title>Blog Create</title>
</head>

<body>

  {% block content %}

  <br>
  <div class="container">
  	<form action="{% url 'blog:postcreate' %}">
  	  <h4>Title</h4>
  	  <input type="text" name="title">
  	  <br>
  	  <br>
  	  <h4>Content</h4>
  	  <textarea cols=40 rows=10 name="body"></textarea>
  	  <br>
  	  <br>
  	  <input class="btn btn-dark" type="submit" value="Submit">
    </form>
  </div>

  {% endblock %}

</body>

blog/templates/blog/post_detail.html
<!-- blog>templates>blog>post_detail.html -->

<head>
  <meta charset="utf-8">
  <title>Blog - {{ object.title }}</title>
</head>
<body>
  <p><strong>{{ object.title }}</strong></p>
  <p>{{ object.content }}</p>

  <p>
    {% if object.get_previous %}
      <a href="{{ object.get_previous.get_absolute_url }}" title="Previous">&larr; {{ object.get_previous }}</a>
    {% endif %}

    {% if object.get_next %}
    | <a href="{{ object.get_next.get_absolute_url }}" title="Next Page">{{ object.get_next }} &rarr;</a>
    {% endif %}
  </p>
  <P>{{ object.mod_date|date:"j F Y" }}</P>
  <br>
  <br>
  <div>
    {{ object.contet|linebreaks }}
  </div>
  <div>
    <a href="{% url 'blog:post_archive' %}">Post Archive</a>
  </div>
</body>

blog/templates/blog/post_list.html
<!-- blog>templates>blog>post_list.html -->

<head>
  <meta charset="utf-8">
  <title>Blog</title>
</head>

<body>
  <h3>Post List</h3>
  <span>
    <a href="{% url 'blog:create' %}">Create</a>
    <a href="{% url 'blog:post_archive' %}">Archive</a>
  </span>

  <p>
    {% for post in posts %}
      <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a>&nbsp;&nbsp;&nbsp;{{ post.mod_date | date:"N d, Y" }}</h3>
    {% endfor %}
  </p>
  <br>
  <div>
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
    {% endif %}

    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}
  </div>
</body>