blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/create', views.create, name='create'),
    path('postcreate', views.postcreate, name='postcreate'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.show_archive, name='post_archive'),
    path('archive/<int:year>', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today'),
]

historydb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('repo/', include('repo.urls')),
    path('blog/', include('blog.urls')),
    path('rest_api_test/', include('rest_api_test.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

repo/urls.py
from django.urls import path

from . import views

app_name = "repo"
urlpatterns = [
    path('', views.index, name='index'),
    path('upload_cli/', views.UploadView.as_view(), name='upload'),
    path('upload/', views.upload, name='upload'),
    path('perf_upload/', views.perf_upload, name='perf_upload'),
    path('<int:perf_file_id>/', views.query, name='query'),
]

repo/models.py
from django.db import models
import jsonfield

# Create your models here.

class PerfFile(models.Model):
    app_name = models.CharField(max_length=200)
    user_name = models.CharField(max_length=200)
    perf_data = jsonfield.JSONField()
    pub_date = models.DateTimeField('date published')

repo/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.http import HttpResponse
from django.http import JsonResponse

from django.template import loader
from .models import PerfFile
from django.shortcuts import render

class UploadView(View):
    def get(self, request):
        #latest_perf_file_list = PerfFile.objects.order_by('-pub_date')[:50]
        #context = {
        #        'latest_perf_file_list': latest_perf_file_list,
        #        }
        #return render(request, 'repo/index.html', context)

        dummy_data = {
            'name': 'HistoryDB',
            'type': 'Repo',
            'job': 'Service'
        }
        return JsonResponse(dummy_data)

    def post(self, request):
        #perfdata = PerfFile()
        #perfdata.app_name = "1234" #request.GET['app_name']
        #perfdata.user_name = "5678" #request.GET['user_name']
        #perfdata.perf_data = "asdf" #request.GET['perf_data']
        #perfdata.pub_date = datetime.now()
        #perfdata.save()

        #print (request.body)

        request_json = json.loads(request.body)
        print (request_json)

        perfdata = PerfFile()
        perfdata.app_name = request_json["app_name"]
        perfdata.user_name = request_json["user_name"]
        perfdata.perf_data = request_json["perf_data"]
        perfdata.pub_date = datetime.now()
        perfdata.save()

        return HttpResponse("Post request")

    def put(self, request):
        print (request.data)
        return HttpResponse("Put request")

    def delete(self, request):
        return HttpResponse("Delete request")


def index(request):
    latest_perf_file_list = PerfFile.objects.order_by('-pub_date')[:50]
    context = {
            'latest_perf_file_list': latest_perf_file_list,
            }
    return render(request, 'repo/index.html', context)

#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    template = loader.get_template('polls/index.html')
#    context = {
#            'latest_question_list': latest_question_list,
#            }
#    return HttpResponse(template.render(context, request))

from repo.models import *
from datetime import datetime
import json
from django.forms.models import model_to_dict
from django.shortcuts import redirect
from django.urls import reverse_lazy

def query(request, perf_file_id):
    obj = PerfFile.objects.get(pk = perf_file_id)
    print (model_to_dict(obj))

    context = {
        "json_detail": model_to_dict(obj)
        }

    return render(request, 'repo/detail.html', context)
    #return JsonResponse(model_to_dict(obj))

    #all_entries = PerfFile.objects.all()
    #print (model_to_dict(all_entries[0]))

    #fb = PerfFile(name = '####', perf_data = json.dumps('{"a":"b"}'), pub_date = datetime.now())
    ##fb = PerfFile(name = '####', pub_date = datetime.now())
    #fb.save()

    #return HttpResponse("SASDFASDF question %s." % perf_file_id)

def upload(request):
    return render(request, 'repo/upload.html')

def perf_upload(request):
    perfdata = PerfFile()
    perfdata.app_name = request.GET['app_name']
    perfdata.user_name = request.GET['user_name']
    perfdata.perf_data = request.GET['perf_data']
    perfdata.pub_date = datetime.now()
    perfdata.save()

    #fb = PerfFile(app_name = '########', perf_data = json.dumps('{"a":"b"}'), pub_date = datetime.now())
    #fb.save()

    return redirect(reverse_lazy('repo:index'))

repo/templates/repo/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <p>History Database Data Details</p>
        <p>
        <pre>{{ json_detail | pprint }}</pre>
        </p>

        <span>
          <a href="{% url 'repo:index' %}">Go to repo</a>
        </span>

    </body>
</html>

repo/templates/repo/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <p>History Database Repository</p>
        <span>
          <a href="{% url 'repo:upload' %}">Upload</a>
        </span>

        {% if latest_perf_file_list %}
        <ul>
        {% for perf_file in latest_perf_file_list %}
          <li>{{ perf_file.pub_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;<a href="/repo/{{ perf_file.id }}/">{{ perf_file.app_name }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p> No performance files are available.</p>
        {% endif %}

    </body>
</html>

repo/templates/repo/upload.html
<!-- blog>templates>blog>post_upload.html -->

<head>
  <meta charset="utf-8">
  <title>Upload performance file</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>

<body>

  {% block content %}

  <br>
  <div class="container">
  	<form action="{% url 'repo:perf_upload' %}">
  	  <h4>Application name</h4>
  	  <input type="text" name="app_name">
  	  <br>
  	  <h4>User name</h4>
  	  <input type="text" name="user_name">
  	  <br>
  	  <h4>Perf data (JSON)</h4>
  	  <textarea cols=40 rows=10 name="perf_data"></textarea>
  	  <br>
  	  <br>
  	  <input class="btn btn-dark" type="submit" value="Submit">
    </form>
  </div>

  {% endblock %}

</body>