blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/create', views.create, name='create'),
    path('postcreate', views.postcreate, name='postcreate'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.show_archive, name='post_archive'),
    path('archive/<int:year>', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today'),
]

historydb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('repo/', include('repo.urls')),
    path('blog/', include('blog.urls')),
    path('rest_api_test/', include('rest_api_test.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

main/urls.py
from django.urls import path
from django.urls import include

from . import views

from django.conf.urls import url
from django.contrib import admin

app_name = "main"
urlpatterns = [
    path('', views.index, name='index'),
    path('acknowledgement/', views.acknowledgement, name='acknowledgement'),
    url(r'^repo/', include('repo.urls')),
    url(r'^blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    #url('^admin/', include('admin.site.urls')),
]

repo/urls.py
from django.urls import path

from . import views

app_name = "repo"
urlpatterns = [
    path('', views.index, name='index'),
    path('upload_cli/', views.UploadView.as_view(), name='upload'),
    path('upload/', views.upload, name='upload'),
    path('perf_upload/', views.perf_upload, name='perf_upload'),
    path('<int:perf_file_id>/', views.query, name='query'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'main/index.html')

def acknowledgement(request):
    print ("!@#!@!@#")
    return render(request,'main/acknowledgement.html')

main/templates/main/acknowledgement.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">
  <title>GPTune History Database</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/starter-template.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">GPTune History DB</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Repository</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Archive</a>
          <a class="dropdown-item" href="#">Performance data</a>
          <a class="dropdown-item" href="#">Surrogate models</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Documentation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Forum</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://github.com/gptune/GPTune/tree/history_db">GPTune</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:acknowledgement' %}">Acknowledgements</a>
      </li>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0"> -->
    <!--   <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"> -->
    <!--   <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button> -->
    <!-- </form> -->
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">
    <h1>Acknowledgements</h1>
    <br>
    <p class="lead">GPTune Copyright (c) 2019, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy) and the University of California, Berkeley. All rights reserved.
    <br>
    If you have questions about your rights to use or distribute this software, please contact Berkeley Lab's Intellectual Property Office at IPO@lbl.gov.
    <br>
    NOTICE. This Software was developed under funding from the U.S. Department of Energy and the U.S. Government consequently retains certain rights. As such, the U.S. Government has been granted for itself and others acting on its behalf a paid-up, nonexclusive, irrevocable, worldwide license in the Software to reproduce, distribute copies to the public, prepare derivative works, and perform publicly and display publicly, and to permit other to do so.
    </p>
    <br><br>
  </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

main/templates/main/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">
  <title>GPTune History Database</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/starter-template.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">GPTune History DB</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Public Repository</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'repo:index' %}">Archive</a>
          <a class="dropdown-item" href="#">Performance data</a>
          <a class="dropdown-item" href="#">Surrogate models</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Documentation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Forum</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://github.com/gptune/GPTune/tree/history_db">Github</a>
      </li>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0"> -->
    <!--   <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"> -->
    <!--   <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button> -->
    <!-- </form> -->
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">
    <h1>GPTune History Database</h1>
    <br>
    <p class="lead"><a href="https://github.com/gptune/GPTune">GPTune</a> is an autotuning framework that relies on multitask and transfer learnings to help solve the underlying black-box optimization problem. GPTune is part of the <a href="https://xsdk.info/ecp/">xSDK4ECP</a> effort supported by the Exascale Computing Project (ECP).
    <br><br>
    The GPTune development team (GPTune-Dev) is developing a history database for GPTune, where all GPTune users will have the option to store their performance data, or download and (re-)use the performance data from the same and other users, to allow GPTune to achieve the best possible performance tuning for widely used codes.
    <br><br>
    This webpage is for GPTune users to share the performance results (called GPTune History Database) of GPTune. </p>
  </div>

  <div class="starter-template">
      <h2>Development Team and Facility</h2>
      <br>
      <a href="https://www.berkeley.edu/"><img src="{% static 'images/UCBerkeleyLogo.png' %}" width=200></a>
      &nbsp;
      &nbsp;
      &nbsp;
      &nbsp;
      <a href="https://www.lbl.gov/"><img src="{% static 'images/BerkeleyLabLogo.png' %}" width=200></a>
      &nbsp;
      &nbsp;
      &nbsp;
      &nbsp;
      <a href="https://www.nersc.gov/"><img src="{% static 'images/NERSCLogo.jpg' %}" width=200></a>
  </div>

  <div class="starter-template">
    <h2>Acknowledgements</h2>
    <br>
    <p class="lead">GPTune Copyright (c) 2019, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy) and the University of California, Berkeley. All rights reserved.
    <br>
    If you have questions about your rights to use or distribute this software, please contact Berkeley Lab's Intellectual Property Office at IPO@lbl.gov.
    <br>
    NOTICE. This Software was developed under funding from the U.S. Department of Energy and the U.S. Government consequently retains certain rights. As such, the U.S. Government has been granted for itself and others acting on its behalf a paid-up, nonexclusive, irrevocable, worldwide license in the Software to reproduce, distribute copies to the public, prepare derivative works, and perform publicly and display publicly, and to permit other to do so.
    </p>
    <br><br>
  </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>